### ISSUE TITLE
Unable to instantiate EthrDID

### ISSUE THREAD

**Issue by gobberr** [uport-project/ethr-did#73] opened 2021-06-01 16:07 UTC
I'm trying to instantiate EthrDID in the following way: 

```
const providerConfig = { rpcUrl: 'https://rinkeby.infura.io/ethr-did' }
const issuer: Issuer = new EthrDID({
  identifier: identity.did, // my did
  privateKey: identity.privateKey, // my private key
  providerConfig  
})
```

I get this error:
```
error TS2351: This expression is not constructable.
Type 'typeof import("/app/node_modules/ethr-did/lib/index")' has no construct signatures.
```

I'm using "ethr-did": "^2.1.4" on package.json

Maybe I'm misconfiguring the providerConfig parameter?
Thanks and best regards

**Comment by mirceanis** [comment] 2021-06-02 10:15
You can use the `rpcUrl` parameter directly in the arguments object for the constructor:
```ts
const issuer: Issuer = new EthrDID({ identifier, privateKey, rpcUrl })
```

If you need to bundle the `providerConfig` as an object, then you can use the spread operator: `...providerConfig`

```ts
const providerConfig = { rpcUrl: 'https://rinkeby.infura.io/<please get an infura project ID>' }
const issuer: Issuer = new EthrDID({
  identifier,
  privateKey,
  ...providerConfig  
})
```

[This section of the readme](https://github.com/uport-project/ethr-did#configuration) details all the parameters you can configure.

If you intend to run on `rinkeby`, it's wise to also specify the `chainNameOrId` parameter:
```ts
const providerConfig = { }
const issuer: Issuer = new EthrDID({
  // ...
  rpcUrl: 'https://rinkeby.infura.io/<please get an infura project ID>',
  chainNameOrId: 'rinkeby'
})
```

**NOTE** The RPC URL you are using (https://rinkeby.infura.io/ethr-did) no longer works, please get a free infura project ID or use an alternative provider.
You can also specify an ethers.js provider directly, like so:
```ts
const issuer: Issuer = new EthrDID({
  // ...
  provider: new InfuraProvider('rinkeby', <infura project ID>),
  chainNameOrId: 'rinkeby'
})
```
See [InfuraProvider](https://docs.ethers.io/v5/api/providers/api-providers/#InfuraProvider) or [AlchemyProvider](https://docs.ethers.io/v5/api/providers/api-providers/#AlchemyProvider)

Closing this. Please reopen if the issue is not resolved

**Comment by gobberr** [comment] 2021-06-03 08:36
Thanks for the answer.

I'm giving as input to the EthrDID constructor an object conforming to the IConfig interface, but I still get the error reported in the screenshot below.

<img width="734" alt="Schermata 2021-06-03 alle 10 25 33" src="https://user-images.githubusercontent.com/27292894/120613064-2613de80-c456-11eb-9a8d-87fbd1464d10.png">

I can't figure out how I can fix it

**Comment by mirceanis** [comment] 2021-06-03 09:07
Does this error only appear in VSCode or is it breaking your build?
This may be obvious already but have you tried a clean build? (clear node_modules, `yarn cache clean`, reimport the project in vscode, etc..)

If it is breaking your build, can you isolate the error in a small project that we could look at?

**Comment by gobberr** [comment] 2021-06-03 09:49
The build breaks and yes I also have already tried to clean up my development environment

You can have a look [here](https://github.com/gobberr/ethr-did-test), running the file `run.ts` with the command `ts-node run.ts`

That's my situation

<img width="785" alt="Schermata 2021-06-03 alle 11 48 43" src="https://user-images.githubusercontent.com/27292894/120625132-ae4bb100-c461-11eb-880d-e4d9228cd31b.png">

**Comment by mirceanis** [comment] 2021-06-03 10:36
I think I see what's happening now, after you shared your project.
the import statement should be `import { EthrDID } from "ethr-did";` instead of `import EthrDID from "ethr-did";`

You seem to have stumbled upon a bug in the docs that are somewhat outdated now.

**Comment by gobberr** [comment] 2021-06-03 10:44
Now it's works, thanks again!

**Closed** 2021-06-03 10:54 UTC
Labels: bug, documentation
